### ISSUE TITLE
Unzipping causes -1 issue

### ISSUE THREAD

**Issue by l2nguyen** [l2nguyen/SuSoAPI#12]
The zip file still unzips but the some datasets are not complete. Gives "In unzip(zip_name, exdir = zip_path) : error -1 in extracting from zip file"

**Comment by ashwinikalantri** [comment]
I tried not unzipping and importing the file from the zipped file.

`data <- read.delim(unz("MGIMSHDSS_1_Tabular_All.zip","MGIMSHDSS.tab"), stringsAsFactors=FALSE)`

This doesn't help either. The number of rows is less here as compared to when I unzip manually and then import.

**Comment by l2nguyen** [comment]
Are you using a Windows machine or a Mac? We did some testing by unzipping the same zip files and there are appears to be no issue for for Windows machines. I am running R version 3.6.1 on Mac OS X 10.14.6 (Mojave). 

Can you try the following steps:
1) setting unzip=FALSE in the dl_* API function
2) Running `unzip(zipfile=[full path to your zip file], exdir=[full path of your desired unzip folder], unzip=getOption("unzip"))` to unzip the file in R

See if you get the same number of rows as when you unzip manually.

**Comment by ashwinikalantri** [comment]
I am using a Mac. R version 3.6.1 on Mac OS X 10.15.1. Will give this a try and get back.

**Comment by ashwinikalantri** [comment]
I tried again using this method and manual unzipping. They have the same number of rows. Will continue to test over the next few days and report if I find any difference.

**Comment by l2nguyen** [comment]
I've tested it with a variety of different zip files of SuSo exports and the number of rows has been the same for all of them. So I've added this fix to the unzipping to the function.

**Comment by ashwinikalantri** [comment]
Tried it a few times. The issue seems to be fixed.
