### ISSUE TITLE
Handle passwords (and user names) that contain special characters

### ISSUE THREAD

**Issue by arthur-shaw** [l2nguyen/SuSoAPI#7]
An authentication problem occurs when the password (or user name) contains a (curl) special character.

Need to find a way to handle these situations better since SuSo admin passwords (which could be use for download requests) consist of random characters, including (curl) special characters.

A problem found in the wild:

Password specified: `r~J20$e@@2`
Password shown in error message: `r~J20@@2`

A few ideas after rapid research:

- **Inject escape characters.** Some, like [this article](https://cleanprogrammer.net/specify-username-and-password-with-special-characters-for-curl-command/), suggest escaping special characters. This could be done by inspecting passwords for special characters, and then inserting an escape character `\` just before the special character.
- **Use encoding.** Others suggest encoding. [This post](https://stackoverflow.com/questions/10060093/special-characters-like-and-in-curl-post-data?rq=1) says to use the curl option to encode the whole payload. [This post](https://stackoverflow.com/questions/39084230/encoding-password-field-for-http-basic-auth) suggests encoding the user name and password only. Need to see if any of these options are available via `httr`.

**Comment by l2nguyen** [comment]
I tried to replicate the issue with several randomly generated passwords with special characters but did not encounter an error. Using RStudio version 1.1.463 with R version 3.5.2. I wonder if this is an issue with using rcall.
